### ISSUE TITLE
Getting a fatal error trying to clone the master branch

### ISSUE THREAD

**Issue by Rod-in-NM** [WaltRitscher/WPF_Controls#1]
I've connected, copied the URL and tried to clone this using VS 2017. It failed with the following error:

Git failed with a fatal error.
unable to access 'https://github.com/WaltRitscher/WPF_Controls.git/': SSL certificate problem: self signed certificate in certificate chain

Have I done something wrong?

**Comment by WaltRitscher** [comment]
Let me check the report and see if it is in a good state.

Walt Ritscher
________________________________

**Comment by Rod-in-NM** [comment]
Hi @WaltRitscher, I just tried cloning the repo again. It worked fine this time. Closing this issue.
